name: CI

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - "src/**"
      - "tests/**"
      - "pyproject.toml"
      - "uv.lock"

jobs:
  typos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5 # v5
      - uses: crate-ci/typos@master

  test-others:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    concurrency:
      group: test-others-${{ github.ref }}-${{ matrix.python-version }}-${{ matrix.pydantic }}
      cancel-in-progress: true

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
        # os: [ubuntu-latest, windows-latest, macos-latest]
        pydantic: ["pydantic-v1", "pydantic-v2"]

    env:
      OS: ubuntu-latest
      PYTHON: ${{ matrix.python-version }}
      UV_NO_SYNC: 1

    steps:
      - uses: actions/checkout@v5

      - name: setup uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }}
          version: "latest"

      - name: Install Dependencies for test group
        run: uv sync --no-dev --locked --group ${{ matrix.pydantic }}

      - name: Run Pytest Others
        run: uv run poe test_others

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          env_vars: OS,PYTHON
          files: ./junit1.xml
          use_oidc: true

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          env_vars: OS,PYTHON
          files: ./coverage1.xml
          use_oidc: true

  test-parsers:
    name: Test Parsers
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    concurrency:
      group: test-parsers-${{ github.ref }}
      cancel-in-progress: true

    env:
      UV_NO_SYNC: 1

    steps:
      - uses: actions/checkout@v5

      - name: setup uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          python-version: 3.12
          version: "latest"

      - name: Setup FFmpeg
        uses: AnimMouse/setup-ffmpeg@v1

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install Dependencies for test group
        run: uv sync --no-dev --locked

      - name: Run Pytest Parsers
        run: uv run poe test_parsers

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          files: ./junit2.xml
          use_oidc: true

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage2.xml
          use_oidc: true

  test-render:
    name: Test Render
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      issues: write
      pull-requests: write
      contents: read
    concurrency:
      group: test-render-${{ github.ref }}
      cancel-in-progress: true

    env:
      UV_NO_SYNC: 1

    steps:
      - uses: actions/checkout@v5

      - name: setup uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          python-version: 3.12
          version: "latest"

      - name: Install Dependencies for test group
        run: uv sync --no-dev --locked

      - name: Run Pytest Render
        run: uv run poe test_render

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          files: ./junit3.xml
          use_oidc: true

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage3.xml
          use_oidc: true

      - name: Find or Create Comment
        if: ${{ github.event.pull_request.number }}
        uses: peter-evans/find-comment@v4
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: "github-actions[bot]"

      - name: Update Comment
        if: ${{ github.event.pull_request.number }}
        uses: peter-evans/create-or-update-comment@v5
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body-path: render_result.md
          edit-mode: replace
