name: CI

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - "src/**"
      - "tests/**"
      - "pyproject.toml"
      - "uv.lock"

jobs:
  typos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5 # v5
      - uses: crate-ci/typos@master

  test-others:
    name: Test
    runs-on: ${{ matrix.os }}
    permissions:
      id-token: write
      contents: read
    concurrency:
      group: test-others-${{ github.ref }}-${{ matrix.python-version }}-${{ matrix.os }}
      cancel-in-progress: true

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
        os: [ubuntu-latest, windows-latest, macos-latest]

    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version }}
      UV_NO_SYNC: 1

    steps:
      - uses: actions/checkout@v5

      - name: setup uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }}
          version: "latest"

      - name: Install Dependencies for test group
        run: uv sync --no-dev --locked

      - name: Run Pytest Others
        run: uv run poe test_others

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          env_vars: OS,PYTHON
          files: ./junit1.xml,./junit2.xml
          use_oidc: true

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          env_vars: OS,PYTHON
          files: ./coverage1.xml,./coverage2.xml
          use_oidc: true

  test-parsers:
    name: Test Parsers
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    concurrency:
      group: test-parsers-${{ github.ref }}-3.12-ubuntu-latest
      cancel-in-progress: true

    env:
      UV_NO_SYNC: 1

    steps:
      - uses: actions/checkout@v5

      - name: setup uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          python-version: 3.12
          version: "latest"

      - name: Setup FFmpeg
        uses: AnimMouse/setup-ffmpeg@v1

      - name: Install Dependencies for test group
        run: uv sync --no-dev --locked

      - name: Run Pytest Parsers
        run: uv run poe test_parsers

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          files: ./junit2.xml
          use_oidc: true

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage2.xml
          use_oidc: true
