name: Test Parse Share Url

on:
  push:
    branches:
      - '*'
      - '**'

jobs:
  parse-url-test:
    runs-on: ubuntu-latest
    env:
      LOG_LEVEL: DEBUG
    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Install uv and set the python version
      uses: astral-sh/setup-uv@v5
      with:
        python-version: ${{ matrix.python-version }}
    
    # - name: Install ffmpeg
    #   run: |
    #     sudo apt-get update
    #     sudo apt-get install -y ffmpeg
    
    - name: Install Dependences 
      run: | 
        uv sync --group test

    - name: Run Bilibili Tests
      run: |
        python -m pytest -v -s tests/test_bilibili.py

    - name: Run Douyin Tests
      run: |
        python -m pytest -v -s tests/test_douyin.py
    
    - name: Run Xiaohongshu Tests
      run: |
        python -m pytest -v -s tests/test_xhs.py
    
    - name: Run Weibo Tests
      run: |
        python -m pytest -v -s tests/test_weibo.py
    
    - name: Run Download tests
      run: |
        python -m pytest -v -s tests/test_download.py
